apiVersion: v1
kind: Service
metadata:
  name: {{ template "keycloakGatekeeper.fullname" . }}
  labels:
    app: {{ template "keycloakGatekeeper.name" . }}
    chart: {{ template "keycloakGatekeeper.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: {{ template "keycloakGatekeeper.name" . }}
    release: {{ .Release.Name }}